Link to dataset - https://datamed.org/display-item.php?repository=0021&id=590ce9ef5152c6571c0cd55f&query=

I. Sleep Stages

	W	Awake
	1	Stage 1
	2	Stage 2
	3	Stage 3
	4	Stage 4
	R	REM


II. Event Indicators


	H	Hypopnea
	HA	Hypopnea with arousal
	OA	Obstructive apnea
	X	Obstructive apnea with arousal
	CA	Central apnea
	CAA	Central apnea with arousal
	L	Leg movements
	LA	Leg movements with arousal
	A	Unspecified arousal
	MT	Movement time
